apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: electric-monitor
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true
    listener 9001
    protocol websockets
