apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
  namespace: electric-monitor
spec:
  selector:
    app: mosquitto
  ports:
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: 1883
    - name: websockets
      protocol: TCP
      port: 9001
      targetPort: 9001
