apiVersion: apps/v1
kind: Deployment
metadata:
  name: electric-monitor-api
  namespace: electric-monitor
  labels:
    app: electric-monitor-api
spec:
  # Начинаем с 1 реплики для тестирования
  replicas: 1
  selector:
    matchLabels:
      app: electric-monitor-api
  template:
    metadata:
      labels:
        app: electric-monitor-api
    spec:
      containers:
      - name: electric-monitor-api
        image: electric-monitor:latest
        # ИСПРАВЛЕНО: Используем локальный образ
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: electric-monitor-config
        - secretRef:
            name: electric-monitor-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 15"]
      terminationGracePeriodSeconds: 30
