apiVersion: v1
kind: Service
metadata:
  name: electric-monitor-api-service
  namespace: electric-monitor
spec:
  selector:
    app: electric-monitor-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
